### ISSUE TITLE
Limit scraping to specific time frame.

### ISSUE THREAD

**Issue by jaymk1** [Dracovian/Discord-Scraper#13]
Hi, I am confused how you are scraping a certain time frame. If i wanted for instance, scrape only the last 24 hours, how would i go about doing this?

**Comment by Dracovian** [comment]
You would have to take the snowflake of the current timestamp and the snowflake of the timestamp 24 hours ago.

I still don't quite understand if Discord is looking for timestamps that corresponds to their timezone or if they work with one's local timezone (I'd imagine the prior one due to the use of Cloudflare's CMS, but that doesn't necessarily mean that they accounted for that in the backend).

The get_day function in the script asks for the day, month, and year and returns the 00:00:00.000 snowflake and the 23:59:59.999 snowflake.

```py
def get_day(day, month, year):
    min_ts = mktime(get_tstruct('%02d %02d %d 00:00:00' % (day, month, year))) * 1000
    max_ts = (mktime(get_tstruct('%02d %02d %d 00:00:00' % (day, month, year))) + 86400.0) * 1000

    return [
        get_snowflake(int(min_ts)),
        get_snowflake(int(max_ts))
    ]
```

**Comment by jaymk1** [comment]
Makes sense. Thanks a lot!
