### ISSUE TITLE
Error 429 too many requests

### ISSUE THREAD

**Issue by emerysteele** [Dracovian/Discord-Scraper#33]
Keep getting: `Unknown exception: HTTP 429 Too Many Requests` when trying to run the script. It will download a little bit, then get this error.

**Comment by emerysteele** [comment]
Resolved by adding sleep(1) to everywhere the script does a request. Discord API limit appears to allow 120 requests per 60 seconds. So sleep(0.5) may also work, but haven't tested.

**Comment by Dracovian** [comment]
See if the experimental branches are functional since I don't exactly know which branch you were having ratelimiting issues with.

**Comment by codekaust** [comment]
How about setting up a central module to send these requests monitoring how many requests are being sent in 60 seconds? The only problem I see here is the following:
If you send 110 requests in 10 seconds and then stop the program and again run it, then there is a chance of exceeding the rate limit. I think this problem exists in the current solution also (sleep(1)), because of which error 429 is quite common using this scraper.

**Comment by Dracovian** [comment]
> If you send 110 requests in 10 seconds and then stop the program and again run it, then there is a chance of exceeding the rate limit. I think this problem exists in the current solution also (sleep(1)), because of which error 429 is quite common using this scraper.

Yes, Discord did change something with their backend and it was something I mentioned in the more recent issue #68.

I probably should go around closing some of these older issues because it has been over a year since this one but unfortunately we still encounter rate limiting and in my tests I haven't been getting any consistency. Sometimes I hit the rate limiter without any of the headers that Discord claims to be sending in their API documentation *(I wonder if this is because I'm targeting an undocumented API endpoint in this script)*.

One thing I could do is catch the HTTP 429 errors and then have it sit there for a while before retrying but even then that'd only be a temporary fix since it wouldn't take long to hit another rate limit afterwards and Discord have been upping the ante for those who are hitting those rate limits often.

**Comment by codekaust** [comment]
I tried to solve it @Dracovian.
I tested my solution in #69. It works for me. Would love to get your comments.
