### ISSUE TITLE
HTTP 404 Not Found

### ISSUE THREAD

**Issue by AleksaDjordjic** [Dracovian/Discord-Scraper#49]
Downloaded the whole main branch, installed Python 3.8.5, modified the JSON as stated and when trying to run the script, I repeatedly get 404
![image](https://user-images.githubusercontent.com/33227154/94351821-2bff2780-005e-11eb-894b-f0e815620aae.png)

From the issues I found here, only problem that it could be is a malformed JSON config file, although I'm pretty sure that its fine, syntax is at least...
```json
{
  "token": "mfa.--random-private-stuff--",
  "agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) discord/0.0.305 Chrome/69.0.3497.128 Electron/4.0.8 Safari/537.36",
  "buffer": 1048576,

  "query": {
    "images": true,
    "files" : true,
    "embeds": true,
    "links" : true,
    "videos": true,
    "nsfw"  : true
  },

  "types": {
    "images": true,
    "videos": true,
    "files" : true,
    "text"  : true
  },

  "directs": {"OtherAcc":"698xxxxxxxxxxxxxxx"},
  "servers": {}
}
```

Kept everything as is, only changed the "token" and "directs" to add a direct message channel that I needed.
Thought that maybe the ID shouldn't be a string, instead a number but turns out that that just produces an error about not being able to join ints or something along those lines... well... ok I guess... I got no clue as to what else it could be

I don't know much about python, but where would be the base to start off debugging?
Has anyone got any clues in the meantime as to why 404 might be produced?
Did a Discord API update break something?

**Comment by Dracovian** [comment]
I would recommend using the [experimental](https://github.com/Dracovian/Discord-Scraper/tree/experimental) or the [experimental requests](https://github.com/Dracovian/Discord-Scraper/tree/experimental_requests) branch over the main branch due to them being far more stable.

I'm likely going to have to refactor this whole repository to make it easier to use and less of a pain to work with since those are the major reasons why I've been inactive in this repository.

Grabbing from direct messages is a bit trickier since copying the ID of the DM channel similarly to how you would copy the ID of a guild does not yield the correct ID value that this script requires. The way that I was able to do this for testing was by opening the Discord site in a browser and then copying the URL for the direct message to get the correct ID.

The JSON file shouldn't be the problem, but then again the longer I sit on this project the more likely an update to the Discord backend will start causing problems with this script.

**Comment by AleksaDjordjic** [comment]
Just checked, and yeah, it is a different ID in the browser URL...
Used that one and its working fine, perfect!

About the experimental, I wanted to try it, but I wasn't sure if I should since no example JSON was supplied and I didn't want to try to bother reading some Python to figure out the structure if it changed since I don't know the language

**Comment by Dracovian** [comment]
My experimental branch replaced the use of JSON configuration with my own custom one that allows me to have comments in the configuration file (which JSON does not allow for code-like comments).

**Comment by AleksaDjordjic** [comment]
Ooh, so that is what that .set was, nice
Didn't see it in experimental_requests, that is the branch that I also checked. Didn't check the normal experimental

**Comment by AleksaDjordjic** [comment]
Just a quick question about those experimental branches, offtopic to the issue though.
Do they not support DM fetching?
Or experimental_requests specifically

**Comment by Dracovian** [comment]
This is from the [current Discord developer reference](https://discord.com/developers/docs/reference#api-versioning): 
![The current Discord API version is 6](https://i.imgur.com/vtk8cWU.png)

So it should read more like this: `/api/v6/channels/{id}/messages`

The Experimental Requests branch is basically using the 3rd party Requests module instead of the http.client module that I've been using since I added Python 3 support back in February 2018.

The way to install 3rd party modules in Python is by using Pip:
```
python -m pip install requests
```

You might require administrative/root privileges to install modules if the Python directory is read-only for your current usergroup (which is usually is by default).

If you're installing Python 3 for Windows and macOS then you'll have the option to install Pip from the installer. If you're installing Python 3 for Linux then you'll have to download the `python-pip` package separately. The command is still the same for installing the requests module (as seen above).

They should support DM fetching by uncommenting the directs array in the discord.set file in the Experimental branch. The Experimental Requests branch uses a more interactive method of setting things up by asking you a bunch of questions and then generating the config JSON file for you. The problem with this approach is that in order to add or remove a guild/channel/DM from the configuration you will essentially have to delete the JSON file and then re-run the whole questionnaire all over again.

I should hopefully have a better solution to this, but I've been saying that for almost a year now.

**Comment by AleksaDjordjic** [comment]
I'm on canary and used it to test all of this with, could that possibly be why its API V8 for me?

>The Experimental Requests branch is basically using the 3rd party Requests module instead of the http.client module that I've been using since I added Python 3 support back in February 2018.
>
>The way to install 3rd party modules in Python is by using Pip:

Yeah, had some troubles figuring that out, managed to find that out later, its similar to node.js, interesting

> The problem with this approach is that in order to add or remove a guild/channel/DM from the configuration you will essentially have to delete the JSON file and then re-run the whole questionnaire all over again.
>
>I should hopefully have a better solution to this, but I've been saying that for almost a year now.

I was thinking of porting this to C# so that I can work with it, looking at your project to see how stuff is done and then implementing hopefully a bit more complex and maybe even a neat UI application for this, if you don't mind?
Will keep it open source on my GitHub as a public repo

**Comment by Dracovian** [comment]
Well the first problem I had to face was that the official API only restricts us to gathering 100-200 posts (considered "bulk" by the API's standards)

So instead I had to use their search functionality which is not documented anywhere in the official API but was easy enough to comprehend after some time.

So essentially this is how the search API works for Discord:

```
/api/v8/guilds/{guild.id}/messages/search?min_id={snowflake for 00:00}&max_id={snowflake for 23:59}&has=image&has=video&has=link&has=embed&has=sound&include_nsfw={true or false}

You can remove every &has= block and the &include_nsfw= block and it'll still work as long as the two snowflakes are the same.
The snowflakes are mentioned in the official API reference: https://discord.com/developers/docs/reference#snowflakes
```

Also I'm not using the Canary build and yet I'm seeing v8 as the API version despite the official API not being up-to-date to show this. I'm a bit upset by this since it's showing some distention between Discord developers and 3rd party developers (such as us).

Even if they didn't have a public API, we'd still have a somewhat easy time making our own API reference from a bit of time with the Chrome developer tools (even for the desktop app which is rendered through Electron which uses headless Chrome to do the HTML+CSS and JS rendering).

So by knowing this you just have to figure out how to send headers on each request (to include the authorization token) and then you'll be mostly ready to make something similar to this script but in any language of your choosing.

I've been looking into Haxe as of late, but [I did attempt to make a Discord scraper like this in the C language](https://github.com/Dracovian/Discord-Scraper-Experiment).

**Comment by AleksaDjordjic** [comment]
>So by knowing this you just have to figure out how to send headers on each request (to include the authorization token) and then you'll be mostly ready to make something similar to this script but in any language of your choosing.

Yeah, this is really easy to do in C#, I know a good library for it: RestSharp
The only thing I need reference for is generally what needs to be sent, I haven't looked over the API docs in a while, only a long time ago when making bots and needing a specific thing.

> I've been looking into Haxe as of late, but I did attempt to make a Discord scraper like this in the C language.

From my personal biased opinion, C++ and C can be messy, but C# is a nice and easy language, you could try it. And if you know Java, you basically know all of the basics of C# too...

**Comment by Dracovian** [comment]
I'm very familiar with Java and my only repository that uses Java is [this one that takes two files and generates a patch that contains the differences between the two and then compresses that patch](https://github.com/Dracovian/JPatcher).

I wasn't too fond of Java and most of the stuff I do in C# is done through dnSpy modifications for Unity games. I'm not completely unfamiliar with C# and I know that Haxe does have a somewhat similar syntax for the most part:

```hx
package;

class Main {
    public static function main() {
        var strings : Array<Strings> = ["Hello", "World"];
        trace(strings);
    }
}
```

As opposed to Java:

```java
package jmain;

public class Main {
    public static void main(String[] args) {
        String[] strings = {"Hello", "World"};
        
        for (String str : strings)
            System.out.println(str);
    }
}
```

---

Think of bitwise operators as bit manipulation, the one that's seen in the snowflake conversion is used to shift the value to the left by 22 bits (as indicated by the direction of the less-than symbols).

Here's a more simplified example of these bitwise operators:

```
00000001 (  1) << 4 means that we're going to shift all bits over by 4 bits to the left to create 00010000.
00010000 (16) >> 4 means that we're going to shift all bits over by 4 bits to the right to create 00000001.
```

The other bitwise operators are logic-based `AND, OR, XOR, NOT` and the best way to describe them is by their truth tables:
![The truth tables for five bitwise operators](https://i.imgur.com/1poPteT.png)

The bitwise logic operators are checked on a bit-by-bit basis (meaning that you're checking the bits of two values):

**AND** will only return 1 if both values are 1. 

**OR** will return 1 if one or both values are 1.

**XOR** will return 1 if only one of the values are 1 (returns 0 if both are the same, hence why this is called "eXclusive OR").

**NOT** will simply invert the bit (1 => 0 and 0 => 1)

You can mix the NOT (inverse) operator with the other ones to invert their truth tables. If you're familiar with Minecraft's Redstone logic then you'll note that this seems very familiar, and that's no coincidence:

![Redstone logic gates](https://i.imgur.com/TTkY4oL.png)

**Comment by AleksaDjordjic** [comment]
That is an interesting way to explain it, thanks.

About Java and Haxe, C# is very similar
```cs
using System;

public class Program 
{
    public static void Main(string[] args) 
    {
        string[] strings = new string[] {"Hello", "World"};
        
        foreach(var str in strings)
            Console.WriteLine(str);
    }
}```

**Comment by AleksaDjordjic** [comment]
> The bot will have to be joined to the server you want to scrape (so this limits the script's functionality to the servers that the bot is currently in, hence why I went through the trouble of having this run off of a user's authorization token which Discord doesn't like very much which I made mention of in the Wiki for this repository.

Was thinking of doing the same, but aren't client and bot API similar, of practically the same?
Just different auth types.

> Also the Discord API will always return data in JSON format. So you can set the Content-Type header to application/json if you really wanted to (this isn't the case all the time, but you could get away with that for a script like this).

I think RestSharp defaults to JSON, it handles all of the request and response stuff for me, its basically 2-3 lines of code to make any request you'd like and it does the heavy lifting.

**Comment by Dracovian** [comment]
Also knowing hexadecimal is very useful as I've used it in the past to make a very quick reference for the limits of signed and unsigned integer values:

```
0xFF =  255 (the maximum value for an unsigned 8-bit value)
0x7F =  127 (the maximum value for a    signed 8-bit value)
0x80 = -128 (the minimum value for a    signed 8-bit value)

0xFFFF =  65535 (maximum unsigned 16-bit value)
0x7FFF =  32767 (maximum   signed 16-bit value)
0x8000 = -32768 (minimum   signed 16-bit value)

0xFFFFFFFF (unsigned 32-bit)
0x7FFFFFFF (  signed 32-bit)
0x80000000 (  signed 32-bit)

0xFFFFFFFFFFFFFFFF (unsigned 64-bit)
0x7FFFFFFFFFFFFFFF (  signed 64-bit)
0x8000000000000000 (  signed 64-bit)
```

---

The only difference between clients and bots according to the official API is in the authorization token [as seen here](https://discord.com/developers/docs/reference#authentication-example-bot-token-authorization-header).

**Comment by AleksaDjordjic** [comment]
> The only difference between clients and bots according to the official API is in the authorization token as seen here.

Perfect, then its gonna be easy!

**Comment by Dracovian** [comment]
I'm back here just to update the issue when it comes to the "outdated API reference" because apparently that is no longer a problem:

![https://imgur.com/JlucCh1](https://i.imgur.com/JlucCh1.png)
