### ISSUE TITLE
Discord-Scraper doesn't create new directory when scraping next channel

### ISSUE THREAD

**Issue by mataha** [Dracovian/Discord-Scraper#57]
I am running the latest code from the `experimental` branch.

Given more than one `guilds` channel entry in `config.json`:

```json
"guilds": {
  "<snip>": [
    "1",
    "2",
    ...
  ]
}
```

Whenever `discord.py` finishes scraping a channel, it doesn't create a new directory for the next one; instead, it continues its work where it started, scrambling scraped data up to that point in the old directory.

It doesn't overwrite existing files, at least.

**Comment by Dracovian** [comment]
That's likely due to the checks I made to the discord.py file on lines 93 and 97.

I added those lines there to lessen the total number of requests being sent to Discord's API server (since every single page that gets searched comes with a request to gather the name of the guild and the channel that's being accessed).

I'll provide a quick patch for this in a few minutes.
