### ISSUE TITLE
Token missing in developer panel

### ISSUE THREAD

**Issue by aeromaxx** [Dracovian/Discord-Scraper#6]
I have just stumbled upon your app, and I have followed the instructions for both the discord website and the discord app, and there is no key called token in LocalStorage? has discord changed something?  I have enabled developer mode and I quit the standalone app completely, and launched it again, but still no token there, lots of other keys are there but nothing named token.

**Comment by Alkheemist** [comment]
I managed to find this page, it looks like they changed how it is stored (or in this case, how it isn't stored)
https://discordhelp.net/discord-token

They scrape the network packet on a refresh to get the token.

**Comment by aeromaxx** [comment]
I've done that, but unsure if the issue is still unresolved, getting these errors.

`$ python3 discord.py
Received HTTP 401 error when gathering JSON data.
Unable to fetch server name from id, so we'll be using 1Ck2Ak0EipQM instead.Received HTTP 401 error when gathering JSON data.
Unable to fetch channel name from id, so we'll be using zCCWHhuYYtgz instead.Received HTTP 401 error when gathering JSON data.`

**Comment by Alkheemist** [comment]
@aeromaxx that is what you get if your token is incorrect. I had that to begin with while I was putting in what I thought was the token in.

Is your 2FA enabled? I have mine enabled, I'm not sure if that affects anything but it might.
Does your JSON file have no empty server or channel entries in it?
The token should start with "mfa." and mine has 84 characters after that. You put in the whole thing, mfa. included so it should look like

"token":  "mfa.XXXXXXXXXXXXXXXXXXXX<obviouslyputyourtokenhereinsteadofthis>XXXXXXXXXXXXXXXXXXXXXXXX"

**Comment by Dracovian** [comment]
@aeromaxx Those errors you're receiving could be due to one of two things:

1. The discord.json file might not be configured correctly (putting a server ID where a channel ID should be and vice-versa).

2. The Discord API has changed (this script was written for v6 Discord API).

Now we can check and see that Discord's API hasn't changed since I've written this script: ![Discord's API is still at version 6](https://i.imgur.com/Gkt4f1M.png)

Now as far as the method of gathering the token is considered, I'll figure out a way to do this consistently and update the README to reflect this change; in the meantime the errors you're receiving when it comes to not being able to get the channel name and server name from the IDs suggests either an invalid server/channel ID or invalid permissions (you can't scrape from servers you're not apart of and channels you can't access).

**Comment by markman641** [comment]
any updates on this? trying to get this working but there is no TOKEN anywhere

**Comment by markman641** [comment]
So I was able to find my token in an "authorization" header slightly differently than the link posted above. Now when I run the script there are no errors & it makes the appropriately named folders, however nothing appears in the folders and the script seems to get hung up.

**Comment by Dracovian** [comment]
I've updated the readme to show how to get one's authorization token in the most recent version of Discord. Open up another issue if this problem persists or if another problem arises.

I thank you for contributing to this project!
