### ISSUE TITLE
Error 429 while resuming

### ISSUE THREAD

**Issue by demib72** [Dracovian/Discord-Scraper#68]
I don't know if it is due to changes at Discord, but I have been getting error code 429 when scraping channels previously done. Increasing the sleep interval to 2 seconds hit the same rate limit on the API. However, increasing it to 6 seconds seems to be fine so far (a few hours as of writing this).

Noting this seems better than making a pull request.

**Comment by Dracovian** [comment]
Discord's official documentation does mention the inclusion of a per-route rate limiter *(meaning that each API call will have its own rate limit in correspondence with the current network load)*

So far in my tests I haven't been able to hit these per-route rate limits since the headers that are set when that is hit are named as such:
```
X-RateLimit-Limit           - The number of requests that can be made.
X-RateLimit-Remaining  - The number of requests that we can make.
X-RateLimit-Reset          - The timestamp at which the rate limit resets.
X-RateLimit-Reset-After - The total time (in seconds) of when the current rate limit bucket will reset.
X-RateLimit-Bucket        - The unique string identifier for the current rate limit bucket.
```

But there is also the global rate limiter that affects all API routes and that comes about whenever requests are sent too fast. If we are globally rate limited then the response headers will include a boolean header named `X-RateLimit-Global` and the message that we will receive from Discord will follow this JSON formatting:
```json
{
    "message": "You are being rate limited.",
    "retry_after": 64.57,
    "global": true
}
```

So it shouldn't be too difficult to implement a simple check in the script to determine whether or not the rate limit is global or per-route and if it's per-route then through the response headers we can determine how to go about scraping the channel with fewest rate limit issues.

So far the official API documentation states 50 requests per second as the limit for bots that aren't either verified or using premium API features *(essentially spending money to Discord to increase this limitation)*. This might not be too helpful in our situation since we're making use of an undocumented API endpoint as well as using regular user tokens as opposed to bot bearer tokens.

The documentation also mentions the number of requests it takes to get temporarily restricted from accessing the Discord API which is about 10,000 per 10 minutes (16.67 requests per second) and the same issue as above comes into play for this very instance as well.

Since Discord is introducing bans for hitting the rate limit too much then this sorta puts me in the position to go straight into figuring out a solution to this ASAP because it'll only be a matter of time before someone posts an issue stating that the use of this script got their account banned due to constantly hitting the rate limit.

**Comment by demib72** [comment]
Thank you for looking into this. If there is anything I can help with, I'll be happy to provide it.
