### ISSUE TITLE
Error 400

### ISSUE THREAD

**Issue by jazzy348** [Dracovian/Discord-Scraper#7]
Hellos

So I have a HUGE Discord that we are trying to backup, and we managed to download over 4000 files, but then we start receiving http 400 errors and we are not sure why any ideas?

Kind regards,
Jazzy

**Comment by Dracovian** [comment]
Well I do know that Discord limits us to 200 pages of search results for whatever reason...

I've never been able to cache complete channels that have over 200 pages of content (not just images, but text is contained in the page count for the search function).

Doing this through the official API limits us even further than what the search function allows. So far I'm hoping that by v7 of the Discord API increases the limits of what the search function and get-channel function but I have my doubts.

**Comment by Dracovian** [comment]
Since the search function allows for us to scroll through the archives by date, I figure that utilizing that feature should circumvent the 200 page limitation of the previous method. Please open up another issue if this problem persists or if another problem arises.

I thank you for contributing to this project!
