### ISSUE TITLE
can somone help me to run it

### ISSUE THREAD

**Issue by Medamine6969** [Dracovian/Discord-Scraper#71]
i got this problem every time i run it 
 C:/Users/my pc/AppData/Local/Microsoft/WindowsApps/python3.9.exe c:/Users/medam/OneDrive/Desktop/Discord-Scraper-experimental/Discord-Scraper-exiscord-Scraper-experimental/discord.py
[ERROR]: Configuration file can not be found at the following location: C:\Users\my pc\config.json

**Comment by Dracovian** [comment]
I've never heard of this script being ran from a OneDrive folder (or any remote storage directory) so I don't know if that is contributing to the error.

The readme for the repo states that you should make a copy of the `config.unmodified.json` file and rename the copy to `config.json` and keep it stored in the same directory as the `discord.py` file.

From there you'll create a new file and name it something like `my.token` or something along those lines and then use the step-by-step tutorial in the readme to obtain your authorization token and then open the `my.token` file to paste the authorization token in there and save it (so it should be a document with one line containing your full authorization token and nothing else).

From there you'll open the `config.json` file and modify it so that it reads something like this:
```json
{
    "tokenfile": "my.token",
    "useragent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) discord/0.0.309 Chrome/83.0.4103.122 Electron/9.3.5 Safari/537.36",
    "buffer": 1048576,

    "options": {
        "validateFileHeaders": false,
        "generateFileChecksums": false,
        "sanitizeFileNames": true,
        "compressImageData": false,
        "compressTextData": false,
        "gatherJSONData": true
    },

    "query": {
        "images": true,
        "files": false,
        "embeds": true,
        "links": false,
        "videos": true,
        "nsfw": true
    },

    "types": {
        "images": true,
        "videos": true,
        "files": true,
        "text": true
    },

    "directs": {},
    
    "guilds": {
        "server id": [
            "channel 1 id",
            "channel 2 id",
            "channel 3 id"
        ]
    }
}
```

And if all is well then simply running the `discord.py` file with your installation of Python should begin to yield results when you see two new folders created, one to store a cache of the JSON data retrieved from the Discord API servers that can be used to re-generate the text and embedded data of the channel(s) you're scraping. The other folder it creates should store the images and videos that the script was able to grab.

**Comment by Medamine6969** [comment]
ok thanks can i contact u  telegram or discord ?
