### ISSUE TITLE
Multiple copies of unique text

### ISSUE THREAD

**Issue by code3x6** [Dracovian/Discord-Scraper#9]
There seems to be an issue where the text scraped is scraped multiple times. Looking at the outputted csv file I see some unique text showing up as many a 3 or 4 times while in other incenses it works perfectly. If I had to guess I'd say it has something to do with the treading module.

**Comment by Dracovian** [comment]
I'm imagining that it has more to do with the offset issues since the offset of 25 applies to the maximum number of images per page in the search results on a test server when I started developing this script.

Again this script is in dire need of an update and I'm currently looking further into this (potentially hoping to fix this while getting more than 200 pages worth of contents).

I might be able to fix this issue by sifting through channels by date rather than by offset.

**Comment by Dracovian** [comment]
I've updated the script to do away with the older method of gathering data, please open another issue if this problem persists or if another problem arises.

I thank you for contributing to this project!
